runtime: python39  # Use the appropriate runtime version for Python
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

instance_class: F2  # Optional: Define the instance class
env_variables:
  EXAMPLE_ENV: "Production"  # Optional: Set environment variables

handlers:
  - url: /.*
    script: auto